

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gestion-tickets-app
    volumes:
      - ./public:/var/www/public
      - ./storage:/var/www/storage
    ports:
      - "9000:9000"
    environment:
      - APP_ENV=production
      - APP_KEY=base64:dRM324nksIpMZFW7vPu20Bet/K7TVITFUZwzRbZzXXs=
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=gestion_tickets
      - DB_USERNAME=root
      - DB_PASSWORD=root

  db:
    image: mysql:8.0
    container_name: gestion-tickets-db
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gestion_tickets
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"

  nginx:
    image: nginx:latest
    container_name: gestion-tickets-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./public:/var/www/public
    ports:
      - "80:80"

volumes:
  db_data: